services:
  service:
    build:
      context: ..
      dockerfile: arithland-bank/Dockerfile
    container_name: arithland_bank_service
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "8000:8000"
    volumes:
      - /var/www/html/arithland_bank/static:/app/staticfiles
    networks:
      - db_network

networks:
  db_network:
    external: true
